module.exports = {
	VILLAGER: "You do not have any special powers, but this makes you less of a target for the monsters. On some maps you might secretely be the Mantis, or be able to feign being the Drunk, however on other maps people might suspect you are the Shade!",
	SEER: "Your win condition is met as soon as you scan a monster, however on most maps you might secretly be the Fool instead. You must decide when it is best to reveal your information to the other members of the town to be successful.",
	BEHOLDER: "Your win condition is met on the third day, however you are a high priority for the monsters to eat. If you feel threatened, you might want to consider revealing what you know and requesting Paladin protection if they are still able to.",
	FOOL: "You do not actually know you are the Fool until slain.",
	PALADIN: "You are safe from being eaten on the first day, so focus on blessing someone you expect the monsters to target. After the first day, you can instead bless someone you suspect to be a monster if you are feeling threatened.",
	HUNTER: "If someone else pretends to be the Hunter, you can simply mark them and reveal their deception publicly. If you die in the process, the likely-monster will be shot, meeting your win condition.",
	MAYOR: "Your vote carries a lot of sway, and most players will follow what you do. Pay attention to what goes on, and decide carefully before voting.",
	CURSED: "If you expect to be eaten by the monsters before the curse is broken, you should consider trying to lead the town astray so that you are in a better position once converted.",
	JESTER: "Think of what other players do that makes you suspicious, and imitate that. Your goal is to get killed and getting eaten does not count, so lynching is usually the most available way to achieve that.",
	MASON: "Once one of the Masons is slain, you may want to consider warning the town of your roles, to help narrow down the monsters.",
	CRYPTKEEPER: "If you can survive the first day or so, you should start revealing your information to the town to help them make sense of who is left alive.",
	APPRENTICE: "Work with the townfolk, but lay low until your role changes.",
	EXECUTIONER: "If you think you know who is a monster, it may be beneficial to let yourself be lynched so that you can redirect it to the suspicious person.",
	GHOUL: "Your ability to see the roles of eaten players can help you identify everyone more quickly than usual, use this to your advantage.",
	LICH: "You are usually the most valuable monster. Try to stay alive as long as possible, even if it means sacrificing less important monsters.",
	SHADE: "Your ability to hide from scans makes it easy to masquerade as a Villager, but the townfolk will eventually grow suspicious of any who remain. Beware that the Beholder does not survive until day 4 if they are present.",
	HELLION: "You learn the role of the person you incinerate, so sometimes it is valuable to kill someone you are unsure of for more information.",
	IMP: "You are the least important monster. Don't be afraid to sacrifice yourself to save other monsters if you need to.",
	ZOMBIE: "As long as the Lich is alive you are mostly untouchable. Do everything you can to keep suspicion off of the Lich.",
	SPECTRE: "Make sure at least 1 Villager remains alive so that your ability can activate when you are slain for the first time.",
	ASSASSIN: "One of your targets is always a monster. If the first two people you slay are not monsters, consider working with the townfolk to lynch the third.",
	TECHIE: "If you are discovered before the third day, try reminding both factions of how risky it can be to kill you.",
	MANTIS: "You do not know you are the Mantis until slain.",
	COURIER: "Send as much mail as possible to reduce your chances of being lynched.",
	DUELIST: "As long as you have more Moxie than the opposing Duelist and can stay alive, you don't have to worry about killing them.",
	ARCHDEMON: "If you can identify them somehow, try binding to a role such as Drunk or Techie that punishes the townfolk for killing them.",
	HAZMAT: "Check the info board every once in awhile to see if the infection has bounced around to somewhere you did not expect.",
	DRUNK: "Be extra cautious not to type anything forbidden. Your life depends on it!",
	BONEWHEEL: "Using your ability effectively is critical to success. It is extremely important that you survive the first day so that you can use it."
}
